[build]
target = "thumbv6m-none-eabi"

# To flash and disconnect:
[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# runner = "cargo flash --chip EFM32HG322F64 --protocol swd --speed 16 --path"

# To attach to RTT logging right after flashing:
runner = "probe-rs run --chip EFM32HG322F64 --protocol swd --speed 16"

# [alias]
# attach = "probe-rs attach --chip EFM32HG322F64 --protocol swd --speed 16"

rustflags = [
  "-C",
  "linker=flip-link",
  "-C",
  "link-arg=--nmagic",
  "-C",
  "link-arg=-Tlink.x",
  "-C",
  "link-arg=-Tdefmt.x",

  # Code-size optimizations.
  #   trap unreachable can save a lot of space, but requires nightly compiler.
  #   uncomment the next line if you wish to enable it
  # "-Z", "trap-unreachable=no",
  "-C",
  "inline-threshold=5",
  "-C",
  "no-vectorize-loops",

  # Optimize for code size, performance notwithstanding.
  "-C", "opt-level=z",
]

[env]
DEFMT_LOG = "debug"

[profile.release]
debug = 2
